# SPDX-License-Identifier: MIT
# Phicomm N1 (armsr/armv8) 专用构建

name: N1

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

permissions: write-all

jobs:
  build:
    name: ARMSR-N1
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ARMSR-N1
      WRT_THEME: bootstrap
      WRT_NAME: ImmortalWRT
      WRT_SSID: ""
      WRT_WORD: ""
      WRT_IP: 192.168.1.99
      WRT_PW: 无
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      WRT_BRANCH: owrt
      WRT_SOURCE: VIKINGYFY/immortalwrt
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      WRT_TEST: ${{inputs.TEST || false}}
